### ISSUE TITLE
Identification : Laissez un commentaire contenant seulement votre nom.

### ISSUE THREAD

**Issue by FreakenK** [udes-ige511-h2016/references#1]
Laissez un commentaire avec notre nom sous ce billet pour que nous puissions vous inviter à l'organisation.

**Comment by Ibeefcake** [comment]
Jean-Francois Waddell

**Comment by Florian22** [comment]
Florian Bonniec

**Comment by phil2396** [comment]
Philippe-Antoine Plante

**Comment by tetris69** [comment]
Éric Bergeron

**Comment by Northik** [comment]
Kevin Labrie

**Comment by xc43** [comment]
Ian Oscar Vasquez Gutierrez

**Comment by SSTCYR** [comment]
Steven St-Cyr

**Comment by FrankGag** [comment]
François Gagnon

**Comment by asgard-thor** [comment]
Jérémy Manceaux

**Comment by mutumba** [comment]
Guimel Mutumba

**Comment by Stousy** [comment]
Simon Tousignant Beaudette

**Comment by CarlosDoRamirez** [comment]
Carlos Ramirez

**Comment by FreakenK** [comment]
Le compte y est, merci à tous !
