### ISSUE TITLE
Les examens: quoi apporter et à quoi s'attendre

### ISSUE THREAD

**Issue by xc43** [udes-ige511-h2016/references#2]
Salut, 
pour certains cours ont a le droit a apporter des notes aux examens. Je me demandais si c'était le cas dans ce cours-ci aussi. De plus, on peut s'attendre à quel genre de questions dans les examens, du code?

**Comment by phil2396** [comment]
+1

**Comment by FreakenK** [comment]
Bonjour,

Nous ne permettons pas les notes de cours aux examens. La difficulté et la portée des questions reflètent ce fait.

Pour ce qui est du type de questions, nous en parlerons plus en détail lors du cours précédent chaque examen. Vous pouvez par contre vous attendre à avoir un/quelques questions qui vous demanderont d'écrire un peu de code (HTML, CSS, Javascript ou backend). Nous encourageons très fortement le fait que tous les membres d'une équipe écrive une partie du code de chaque TP qui en demande.
