### ISSUE TITLE
Équipes Devoir 1

### ISSUE THREAD

**Issue by FreakenK** [udes-ige511-h2016/references#3]
Indiquez les noms des membres des équipes pour le Devoir 1.

**Comment by tetris69** [comment]
Éric Bergeron
Steven St-Cyr
Kevin Labrie

**Comment by mutumba** [comment]
Guimel Mutumba et Carlos Ramirez

**Comment by xc43** [comment]
Philippe-Antoine Plante
Ian Oscar Vasquez Gutierrez
Jean-Francois Waddell

**Comment by Stousy** [comment]
Simon Tousignant Beaudette et Francois Gagnon

**Comment by Florian22** [comment]
Florian Bonniec et Jérémy Manceaux

**Comment by FreakenK** [comment]
Le compte y est, merci à tous !

**Comment by Ibeefcake** [comment]
Salut, Il semble que je n'ai pas été ajouté à mon équipe correctement. 
Voici mon équipe : 
phil2396
xc43
Ibeefcake     <---- ça c'est moi, ça comment par un i majuscule

Merci !

**Comment by allaire** [comment]
@Ibeefcake Ok peux-tu me dire si ca fonctionne maintenant.

@FreakenK Peut-être juste ajuster le username dans les scripts, car j'ai fait les manipulations à bras.

Merci!

**Comment by Ibeefcake** [comment]
Bonjour,

Ça fonctionne !!

Merci beaucoup.

J-F Waddell
